### ISSUE TITLE
Filter issue: adblocker detected on notebookcheck.net

### ISSUE THREAD

**Issue by Gandalf-The-Wise** [uBlockOrigin/uBOL-issues#11] opened 2022-10-18 18:48 UTC
Running uBlock Origin Lite 0.1.22.10175 as only adblocker in Microsoft Edge I get as of today:

![image](https://user-images.githubusercontent.com/112940078/196518038-7cb6876f-f9d7-4b3c-a955-0f4a49570fb2.png)

**Comment by gorhill** [comment] 2022-10-18 19:14
Entity syntax-based scriptlet injection filters aren't supported:

    notebookcheck.*##+js(no-setTimeout-if, .call(null), 10)

This is the filter which does the work on this page.

**Comment by gorhill** [comment] 2022-10-18 19:21
> This is the filter which does the work on this page.

Or so I thought.

**Comment by gorhill** [comment] 2022-10-18 19:29
I see this filter in uBO filters:

    @@||notebookcheck.net^$script,1p

However, I can't find a corresponding DNR rule, the only one I find using `notebookcheck.net` is:

```
{
 "action":{"type":"allow"},
 "condition":{
  "initiatorDomains":["notebookcheck-ru.com","notebookcheck.com","notebookcheck.net"],
  "requestDomains":["notebook-check.com","notebookcheck-ru.com"],
  "resourceTypes":["script"]
 },
 "id":18291
}
```

Which is not a match. I need to investigate more.

**Comment by mapx-** [comment] 2022-10-18 19:38
yes, that exception is missing, however using the last [uBOLite_0.1.22.10185](https://github.com/gorhill/uBlock/releases/tag/uBOLite_0.1.22.10185)

I cannot reproduce anymore

The triggering thing would be blocking (which easylist does not block)
`notebookcheck.net/fileadmin/templates/js/nbc-ads-ns.js`

**Comment by gorhill** [comment] 2022-10-18 19:40
> that exception is missing

Yes, that's what I am seeing using the [SNFE: DNR] button in the dev tools of uBO. It does appear in there, but not in the final ruleset of uBOLite.

**Comment by mapx-** [comment] 2022-10-18 19:43
but ... who is blocking `notebookcheck.net/fileadmin/templates/js/nbc-ads-ns.js` ?

**Comment by gorhill** [comment] 2022-10-18 19:49
After badfiltering the exception, I see `&ad_url=` causing the blocking.

**Comment by mapx-** [comment] 2022-10-18 19:50
right, getting now

**Comment by mapx-** [comment] 2022-10-18 19:59
I don't understand anymore

I cannot find `&ad_url=`  in EL and now the anti adb is not triggered anymore in uBO

**Comment by mapx-** [comment] 2022-10-18 20:00
That's why 10185 does not get any anti adb

**Comment by gorhill** [comment] 2022-10-18 20:08
It's just luck, there is a flaw in the code in there that would overwrite valid DNR rules with invalid entries, if not the one here, then some others are being clobbered. This will be fixed in next release.

**Comment by gorhill** [comment] 2022-10-18 20:09
`&ad_url=` is the fifth filter from the top of EasyList, it's been there since a long time.

**Comment by mapx-** [comment] 2022-10-18 20:11
> using the [SNFE: DNR] button in the dev tools of uBO

I don't know what button is that 1  ?!

**Closed** 2022-10-18 20:14 UTC

**Comment by gorhill** [comment] 2022-10-18 20:23
> what button is that

Dashboard => _Support_ pane => _More_ button in troubleshooting section => SNFE: DNR

**Comment by mapx-** [comment] 2022-10-18 20:36
oh, in the dev build of uBO
